version: '3'

services:
  client:
    image: fs-gui-client
    build:
      dockerfile: ./client/Dockerfile
    ports:
      - "3000:3000"
    networks:
      - fs-gui-network
    volumes:
      - ./client:/app
    depends_on:
      - server

  server:
    image: fs-gui-server
    build:
      dockerfile: ./server/Dockerfile
    ports:
      - "5000:5000"
    networks:
      - fs-gui-network
    volumes:
      - ./server:/app
    depends_on:
      - mongo

  mongo:
    image: mongo:7.0.5-jammy
    ports:
      - "27017:27017"
    networks:
      - fs-gui-network
    volumes:
      - mongo-data:/data/db

networks:
  fs-gui-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
